idf_component_register(SRCS
                        "main.cpp"
                        "autopilot_modes.cpp"
                        "autopilot_state.cpp"
                        "lateral_state.cpp"
                        "vertical_state.cpp"
                        "serial_connector.cpp"
                        "serial_utils.cpp"
                        "protocol_utils.cpp"
                        
                    INCLUDE_DIRS ".")
